### ISSUE TITLE
Mobile app spec

### ISSUE THREAD

**Issue by vishnuravi** [techforthepeople/NAVI-mobile#1]
For patients:
- Periodically update the patient's GPS location on the backend
- Upload data from HealthKit to the backend

For EMTs:
- Register a new patient
- Update patient's vitals
- View dashboard and map of all patients

For both:
- Search for any bluetooth trackers assigned to patients in the area and update their GPS coordinates on the backend

**Comment by ghost** [comment]
Which of these did ya get done so far?

**Comment by vishnuravi** [comment]
So far getting the GPS data and the health data from HealthKit.
